spring:
  datasource:
    username: northbr
    password: shtmqmfltwl_1266
   #url: jdbc:postgresql://localhost:5432/shop
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: utf-8

  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          Charset: utf-8
          useUnicode: true
        jdbc.lob.non_contextual_creation: true

  freemarker:
    cache: false

  devtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
